# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '10.0'

pod 'MJRefresh'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'MMNumberKeyboard'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'DZNEmptyDataSet'
pod 'JPush'
pod 'MJExtension'
pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'
pod 'WCDB'
pod 'YYText', '~> 1.0.7'
pod 'XWHUDManager'
pod 'OneDriveSDK', '~> 1.3.0'
pod 'ZWPullMenuView'
pod 'SAMKeychain'
target 'BOS' do

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for BOS

target 'BOSTests' do
inherit! :search_paths
# Pods for testing
end

target 'BOSUITests' do
inherit! :search_paths
# Pods for testing
end

end

